#!/usr/bin/python
"""jukebox - translates serial data to commands.
    Copyright (C) 2012 Ali Raheem

    This program is part of jukebox.

    Jukebox is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Jukebox is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import serial, os, sys, sqlite3, re

dbName = "db"
serialDevice = "/dev/RFIDreader"
regex = re.compile('([a-fA-F0-9])+')
lastTag = 0
s = 0
db = 0
c = 0

def parse(code):
#Should return a plain string used as the SQL tag.
	global regex
	index = regex.search(code).span()
	return code[index[0]:index[1]]

def init_serial():
	global s
	s = serial.Serial(serialDevice, 115200)
	s.open()

def init_db():
	global db
	global c
	try:
		db = sqlite3.connect(dbName)
	except sqlite3.OperationalError:
		print "Fatal: Error could not find DB!"
		sys.exit(1)
		
	c = db.cursor()
	c.execute("select * from tags")
	l = c.fetchall()
	print "%d tags known."%len(l)


def play(code):
	global lastTag
	c.execute('select cmd,name from tags where tag=?',(code,))
	result = c.fetchone()
	if(result):
		cmd = result[0]
		name = result[1]
		lastTag = code
		print "Loading %s..."%name
		os.system(cmd)
	else:
		print "Error: Tag not found!"
		return 0

def wait():
	while 1:
		if(s.inWaiting()):
			code =  s.read(s.inWaiting())
			code = parse(code)
			print "Read code %s..."%code
			if(code != lastTag):
				play(code)
			s.flushOutput()
def main():
	init_db()
	init_serial()
	wait()

if __name__ == "__main__":
        sys.exit(main())


