#!/usr/bin/python
import serial, os, sys, sqlite3, re

dbName = "db"
serialDevice = "/dev/RFIDreader"
regex = re.compile('([a-fA-F0-9])+')
lastTag = 0
s = 0
db = 0
c = 0

def parse(code):
#Should return a plain string used as the SQL tag.
	global regex
	index = regex.search(code).span()
	return code[index[0]:index[1]]

def init_serial():
	global s
	s = serial.Serial(serialDevice, 115200)
	s.open()

def init_db():
	global db
	global c
	db = sqlite3.connect(dbName)
	c = db.cursor()
	try:
		c.execute("select * from tags")
	except sqlite3.OperationalError:
		print "Fatal: Error could not find DB!"
		sys.exit(1)
	l = c.fetchall()
	print "%d tags known."%len(l)


def play(code):
	global lastTag
	c.execute('select cmd,name from tags where tag=?',(code,))
	result = c.fetchone()
	if(result):
		cmd = result[0]
		name = result[1]
		lastTag = code
		print "Loading %s..."%name
		os.system(cmd)
	else:
		print "Error: Tag not found!"
		return 0

def wait():
	while 1:
		if(s.inWaiting()):
			code =  s.read(s.inWaiting())
			code = parse(code)
			print "Read code %s..."%code
			if(code != lastTag):
				play(code)
			s.flushOutput()
def main():
	init_db()
	init_serial()
	wait()

if __name__ == "__main__":
        sys.exit(main())


